[features]
seeds = false
skip-lint = false

[programs.localnet]
toto_slots = "EgjsT9zhSjfrTMXo3vN5Evp5iSA4RWu6BdKk1oMj3ALm"

[programs.devnet]
toto_slots = "EgjsT9zhSjfrTMXo3vN5Evp5iSA4RWu6BdKk1oMj3ALm"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/syoo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
custom-script-test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/create.ts"

